<?php

//Nota de venta
$condiciones_1 = 'FAVOR DE PRESENTAR ESTA NOTA PARA EMPEZAR EL PROCEDIMIENTO ADECUADO PARA GARANTIA. SI NO SE PRESENTA LA NOTA NO SE PODRA SEGUIR EL PROCESO;';
$condiciones_2 = "GARANTÍA DE UN AÑO EN DEFECTO DE FABRICA A PARTIR DE LA FECHA DE COMPRA;PARA SER VALIDA LA GARANTIA NO DEBE PRESENTAR: GOLPES, CORTES PROVOCADOS POR MAL MANEJO, PRESION DE AIRE INADECUADA, EXCESO DE PESO, PONCHADURA CON OBJETO PUNZANTE ETC. ";
$condiciones_3 = ' EN MALA INSTALACION SOLAMENTE SERA VALIDA LA GARANTIA DENTRO DEL PRIMER MES DESPUES DE LA COMPRA, SI TIENE PARCHE AUTOMATICAMENTE PIERDE LA GARANTIA; EN CASO DE PROCEDER GARANTIA SE COBRARÁ EL DESGASTE SI ES EL CASO; TIEMPO ESTIMADO DE RESPUESTA DE 1-2 SEMANAS. APLICA RESTRICCIONES. NO SE ACEPTAN DEVOLUCIONES DESPUES DE QUE LA LLANTA SE HA RODADO.';

$condiciones_generales = 'GARANTÍA DE UN AÑO CONTRA DEFECTO DE FABRICACION; PARA SER VALIDA 
LA LLANTA: NO GOLPES, NO CORTES PROVOCADOS POR MAL MANEJO, PRESION DE AIRE INADECUADA, EXCESO DE PESO, 
PONCHADURA CON OBJETO PUNZANTE ETC. A PARTIR DE ESTA FECHA FAVOR DE PRESENTAR ESTA NOTA PARA EMPEZAR EL 
PROCEDIMIENTO ADECUADO PARA GARANTIA. SI NO SE PRESENTA LA NOTA NO SE PODRA SEGUIR EL PROCESO; EN MALA INSTALACION 
SOLAMENTE SERA VALIDA LA GARANTIA DENTRO DEL PRIMER MES DESPUES DE LA COMPRA, SI TIENE PARCHE AUTOMATICAMENTE PIERDE 
LA GARANTIA; EN CASO DE PROCEDER GARANTIA SE COBRARÁEL DESGASTE SI ES EL CASO; TIEMPO ESTIMADO DE RESPUESTA DE 1-2 SEMANAS. 
 VENTAS DE APARTADO: EL PLAZO PARA PAGAR ES DE 1 MES, EN CASO DE NO CUMPLIR EL PAGO A TIEMPO EL MONTO DEL ADELANTO NO SERÁ 
 REEMBOLSABLE. APLICA RESTRICCIONES.';

//Creditos
$text = 'FAVOR DE PRESENTAR ESTA NOTA PARA EMPEZAR EL PROCEDIMIENTO ADECUADO PARA GARANTIA. SI NO SE PRESENTA LA NOTA NO SE PODRA SEGUIR EL PROCESO; ';
$text2 = ' GARANTÍA DE UN AÑO EN DEFECTO DE FABRICA A PARTIR DE LA FECHA DE COMPRA;PARA SER VALIDA LA GARANTIA NO DEBE PRESENTAR: GOLPES, CORTES';
$text3 = ' PROVOCADOS POR MAL MANEJO, PRESION DE AIRE INADECUADA, EXCESO DE PESO, PONCHADURA CON OBJETO PUNZANTE ETC';
$text4 = ' EN MALA INSTALACION SOLAMENTE SERA VALIDA LA GARANTIA DENTRO DEL PRIMER MES DESPUES DE LA COMPRA';
$text5 = ' ';
$text6 = ' SI TIENE PARCHE AUTOMATICAMENTE PIERDE LA GARANTIA; EN CASO DE PROCEDER GARANTIA SE COBRARÁ EL DESGASTE SI ES EL CASO';
$text7 = ' TIEMPO ESTIMADO DE RESPUESTA DE 1-2 SEMANAS. APLICA RESTRICCIONES. NO SE ACEPTAN DEVOLUCIONES DESPUES DE QUE LA LLANTA SE HA RODADO. APLICA RESTRICCIONES.';
?>